USE DATABASE ABCD_POC_DB;
USE SCHEMA ABCD_SILVER;

CREATE TABLE IF NOT EXISTS POC_TASK1_VERIFICATION (
    VERIFICATION_ID VARCHAR DEFAULT UUID_STRING(),
    EXECUTED_AT     TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS          VARCHAR DEFAULT 'TASK_1_PASSED'
);

INSERT INTO POC_TASK1_VERIFICATION (STATUS) VALUES ('TASK_1_PASSED');