-- 1. Create Dedicated Roles
CREATE ROLE IF NOT EXISTS DBT_DEVELOPER_ROLE;
CREATE ROLE IF NOT EXISTS DBT_CICD_PROD_ROLE;

-- 2. Grant roles to SYSADMIN hierarchy
GRANT ROLE DBT_DEVELOPER_ROLE TO ROLE SYSADMIN;
GRANT ROLE DBT_CICD_PROD_ROLE TO ROLE SYSADMIN;

-- 3. Warehouse Usage
GRANT USAGE ON WAREHOUSE W_TRANSFORM_POC TO ROLE DBT_DEVELOPER_ROLE;
GRANT USAGE ON WAREHOUSE W_TRANSFORM_POC TO ROLE DBT_CICD_PROD_ROLE;

-- 4. Database Access
GRANT USAGE ON DATABASE ABCD_POC_DB TO ROLE DBT_DEVELOPER_ROLE;
GRANT USAGE ON DATABASE ABCD_POC_DB TO ROLE DBT_CICD_PROD_ROLE;

-- 5. Read-Only Access for Developers on Raw & Production Schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE ABCD_POC_DB TO ROLE DBT_DEVELOPER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ABCD_POC_DB TO ROLE DBT_DEVELOPER_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE ABCD_POC_DB TO ROLE DBT_DEVELOPER_ROLE;

-- 6. Grant Full Write Access on Personal Developer Schemas
CREATE SCHEMA IF NOT EXISTS ABCD_POC_DB.DBT_DEV_SANDBOX;
GRANT ALL PRIVILEGES ON SCHEMA ABCD_POC_DB.DBT_DEV_SANDBOX TO ROLE DBT_DEVELOPER_ROLE;

-- 7. Full Deployment Access for CI/CD Pipeline ONLY
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ABCD_POC_DB TO ROLE DBT_CICD_PROD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ABCD_POC_DB TO ROLE DBT_CICD_PROD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ABCD_POC_DB TO ROLE DBT_CICD_PROD_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE ABCD_POC_DB TO ROLE DBT_CICD_PROD_ROLE;

-- 8. Assign Developer Role to your user
GRANT ROLE DBT_DEVELOPER_ROLE TO USER "TUSH";

USE ROLE ACCOUNTADMIN;

GRANT CREATE SCHEMA ON DATABASE ABCD_POC_DB TO ROLE DBT_DEVELOPER_ROLE;