version: 2

models:
  - name: fct_sample_event
    description: "Accessioning events and turnaround time fact table"
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: qc_status
        tests:
          - accepted_values:
              values: ['PASS', 'FAIL', 'FLAGGED']
      - name: turnaround_time_minutes
        tests:
          - not_null

  - name: dim_department
    description: "Hospital department dimension"
    columns:
      - name: dept_id
        data_tests:
          - unique
          - not_null
      - name: dept_name
        data_tests:
          - not_null