name: abcd_medallion_transforms
version: 1.0.0
config-version: 2
profile: ABCD
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  abcd_medallion_transforms:
    +materialized: table