ABCD:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DBT_DEVELOPER_ROLE
      database: ABCD_POC_DB
      warehouse: W_TRANSFORM_POC
      schema: DBT_DEV_SANDBOX
      threads: 4
      client_session_keep_alive: False

    uat:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DBT_DEVELOPER_ROLE
      database: ABCD_POC_DB
      warehouse: W_TRANSFORM_POC
      schema: ABCD_UAT
      threads: 4
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DBT_CICD_PROD_ROLE
      database: ABCD_POC_DB
      warehouse: W_TRANSFORM_POC
      schema: ABCD_SILVER
      threads: 4
      client_session_keep_alive: False