ABCD:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: snowflake
      # In GitHub Actions: reads env_var
      # In Snowflake UI: defaults to current account/user context
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'SDHYXTX-CNC63641') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'TUSH') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DBT_DEVELOPER_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'ABCD_POC_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'W_TRANSFORM_POC') }}"
      schema: DBT_DEV_SANDBOX
      threads: 4
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'DBT_CICD_PROD_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'ABCD_POC_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'W_TRANSFORM_POC') }}"
      schema: ABCD_SILVER
      threads: 8
      client_session_keep_alive: False